import Signin from "@/components/auth/signin/Signin";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Sign In ",
  description: "Generated by create next app",
};

const page = () => {
  return <Signin />;
};

export default page;
