import Signup from "@/components/auth/signup/Signup";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "সাইন আপ",
  description: "Generated by create next app",
};

const page = () => {
  return <Signup />;
};

export default page;
